name: Shell Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            shellcheck \
            openssl \
            curl \
            wget \
            zsh

      - name: Run shellcheck
        run: shellcheck src/cert-manager.sh scripts/*.sh

      - name: Run tests
        run: |
          bats test/test_*.bats
          bats test/shell_compatibility.bats
          bats test/*.bats
